
apiVersion: metrics.keptn.sh/v1alpha3
kind: KeptnMetricsProvider
metadata:
  name: dynatrace
spec:
  type: dynatrace
  targetServer: "TENANTURL_TOREPLACE"
  secretKeyRef:
    name: dynatrace
    key: dt_api_token